name: Deploy to Azure Container Apps
on:
  push:
    branches: [azure-prod]
    paths:
      - "**"
      - ".github/workflows/speck-container-AutoDeployTrigger-d468cca2-1495-4570-b66b-a73ca441c2fb.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPECKCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPECKCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPECKCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: speckcons.azurecr.io
          registryUsername: ${{ secrets.SPECKCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPECKCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: speck-container
          resourceGroup: speck
          imageToBuild: speckcons.azurecr.io/speck-container:${{ github.sha }}
          targetPort: 4000
          ingress: external
          containerName: bootstrap-container-pre-deployment
